version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  webapi:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    ports:
     - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local